services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/app:/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - .:/app
      - ./dags:/opt/airflow/dags
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/app:/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - .:/app
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: airflow webserver
    depends_on:
     - airflow-init

  airflow-scheduler:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/app:/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - .:/app
      - ./dags:/opt/airflow/dags
    command: airflow scheduler
    depends_on:
      - airflow-init

volumes:
  airflow_data:
  postgres_data: